### ISSUE TITLE
CREATE TABLE

### ISSUE THREAD

**Issue by hanez** [webworks-nuernberg/ZipGeoDBDe#1]
Ein DROP TABLE IF EXISTS und CREATE TABLE am Anfang waere noch toll damit man die Tabelle nicht von Hand anlegen muss... ;)

Denoch vielen Dank fuer diesen Datensatz!

**Comment by antondachauer** [comment]
Danke für den Hinweis, ist jetzt hinzugefügt!

**Comment by hanez** [comment]
Dankeschoen...! :)
