### ISSUE TITLE
zip code zu kurz

### ISSUE THREAD

**Issue by Buffen** [webworks-nuernberg/ZipGeoDBDe#2]
in der ZipGeoDBDe sind mir im Dump direkt 3 Fehler aufgefallen.

Bei den Datensätze der Orte

7162	3300	Braunschweig	52.26902	10.52596	0000-00-00 00:00:00
7456	3388	Bad Harzburg	51.8998	10.5622	0000-00-00 00:00:00
9824	3000	Hannover	52.38447	9.72693	0000-00-00 00:00:00

ist die PLZ (zip) nur 4 Zeichen lang.

**Comment by antondachauer** [comment]
Danke für den Hinweis, das wird in Kürze korrigiert!
