### ISSUE TITLE
CSV-Datei

### ISSUE THREAD

**Issue by svenpeters** [webworks-nuernberg/ZipGeoDBDe#4]
Nicht jeder hat MySQL im Einsatz, eine CSV-Datei wäre schön.
Falls erwünscht, folgt ein Pull-Request.

**Comment by antondachauer** [comment]
Ja Gerne! :)

Von: svenpeters [mailto:notifications@github.com]
Gesendet: Sonntag, 21. Februar 2016 20:35
An: webworks-nuernberg/ZipGeoDBDe <ZipGeoDBDe@noreply.github.com>; Anton Dachauer <adachauer@webworks-nuernberg.de>
Betreff: [ZipGeoDBDe] CSV-Datei (#4)


Nicht jeder hat MySQL im Einsatz, eine CSV-Datei wäre schön.
Falls erwünscht, folgt ein Pull-Request.

**Comment by antondachauer** [comment]
Danke für den Pull-Request.

Spaltennamen für die CSV-Dateien wären noch ganz praktisch, aber nicht zwingend erforderlich ;)
